import { MetadataRoute } from 'next'

const BASE_URL = 'https://saren.ai'

const routes = [
  '/',
  '/about',
  '/about/clients',
  '/about/expertise',
  '/ai-orchestration',
  '/brand',
  '/contact',
  '/feature',
  '/feature/psylocke-timeline',
  '/playbooks/b2b-marketing-framework',
  '/playbooks/brand-style-guide-page-builder',
  '/playbooks/cmo-content-marketing-pipeline',
  '/playbooks/cmo-gtm-playbook',
  '/playbooks/daily-executive-gsd-stack',
  '/playbooks/digital-dominance-marketing-system',
  '/playbooks/learning-mastery-sequence',
  '/playbooks/linkedin-prospect-dashboard',
  '/playbooks/mckinsey-strategy-suite',
  '/playbooks/personal-bio-brand-builder',
  '/playbooks/research-intelligence-pipeline',
  '/playbooks/self-discovery-mindset-journey',
  '/playbooks/sora2-samurai-creative-series',
  '/playbooks/viral-content-hook-trilogy',
  '/case-studies',
  '/case-studies/10-touch-sales-play',
  '/case-studies/120-day-content-journey',
  '/case-studies/authority-engineering',
  '/playbooks/b2b-marketing-framework/brand-promise',
  '/playbooks/b2b-marketing-framework/brand-voice-tone',
  '/playbooks/b2b-marketing-framework/campaign-brief',
  '/playbooks/b2b-marketing-framework/case-study-framework',
  '/playbooks/b2b-marketing-framework/channel-strategy',
  '/playbooks/b2b-marketing-framework/content-formats-repurposing',
  '/playbooks/b2b-marketing-framework/elevator-pitch',
  '/playbooks/b2b-marketing-framework/hooks-taglines',
  '/playbooks/b2b-marketing-framework/ideal-customer-profile-icp',
  '/playbooks/b2b-marketing-framework/marketing-dashboard',
  '/playbooks/b2b-marketing-framework/marketing-kpis-metrics',
  '/playbooks/b2b-marketing-framework/message-map',
  '/playbooks/b2b-marketing-framework/mission-vision-values',
  '/playbooks/b2b-marketing-framework/nurture-sequence-strategy',
  '/playbooks/b2b-marketing-framework/objection-handling-scripts',
  '/playbooks/b2b-marketing-framework/positioning-statement',
  '/playbooks/b2b-marketing-framework/quarterly-business-review',
  '/playbooks/b2b-marketing-framework/sales-enablement-plan',
  '/playbooks/b2b-marketing-framework/sales-playbook-outline',
  '/playbooks/b2b-marketing-framework/strategic-messaging-pillars',
  '/playbooks/b2b-marketing-framework/target-market-competitive-landscape',
  '/playbooks/b2b-marketing-framework/unique-value-proposition-uvp',
  '/playbooks/b2b-marketing-framework/website-copy-home-landing',
  '/playbooks/hybrid-lead-scoring',
  '/case-studies/dynamic-nurture',
  '/case-studies/executive-dashboard',
  '/playbooks/gtm-budget-calculator',
  '/case-studies/intent-data',
  '/playbooks/its-good-to-be-pitched',
  '/playbooks/roi-simulator',
  '/case-studies/sovereign-personas',
  '/case-studies/thought-leadership-development',
  '/signal-state',
  '/signal-state/architecture',
  '/signal-state/framework',
  '/signal-state/signal-library',
  '/signal-state/use-cases',
  '/signal-state/use-cases/cybersecurity',
  '/signal-state/use-cases/independent-creative',
  '/signal-state/use-cases/org-alignment',
]

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: route === '/' ? 1.0 : 0.7,
  }))
}
