export interface ComicData {
    id: string;
    image: string;
    publisher: string;
    title: string;
    volume: string;
    issueNumber: string;
    releaseDate: string;
}

export const comicsData: ComicData[] = [
    {
        id: "uncanny-1-251",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_1_251.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 1",
        issueNumber: "#251",
        releaseDate: "November 1989",
    },
    {
        id: "uncanny-1-255",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_1_255.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 1",
        issueNumber: "#255",
        releaseDate: "December 1989",
    },
    {
        id: "uncanny-1-256",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_1_256.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 1",
        issueNumber: "#256",
        releaseDate: "December 1989",
    },
    {
        id: "uncanny-1-257",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_1_257.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 1",
        issueNumber: "#257",
        releaseDate: "January 1990",
    },
    {
        id: "uncanny-1-258",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_1_258.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 1",
        issueNumber: "#258",
        releaseDate: "February 1990",
    },
    {
        id: "xmen-2-17",
        image: "/psylocke-backstory/X-Men_Vol_2_17.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#17",
        releaseDate: "February 1993",
    },
    {
        id: "xmen-2-18",
        image: "/psylocke-backstory/X-Men_Vol_2_18.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#18",
        releaseDate: "March 1993",
    },
    {
        id: "xmen-2-19",
        image: "/psylocke-backstory/X-Men_Vol_2_19.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#19",
        releaseDate: "April 1993",
    },
    {
        id: "xmen-2-20",
        image: "/psylocke-backstory/X-Men_Vol_2_20.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#20",
        releaseDate: "May 1993",
    },
    {
        id: "xmen-2-21",
        image: "/psylocke-backstory/X-Men_Vol_2_21.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#21",
        releaseDate: "June 1993",
    },
    {
        id: "xmen-2-22",
        image: "/psylocke-backstory/X-Men_Vol_2_22.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#22",
        releaseDate: "July 1993",
    },
    {
        id: "xmen-2-23",
        image: "/psylocke-backstory/X-Men_Vol_2_23.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#23",
        releaseDate: "August 1993",
    },
    {
        id: "xmen-2-24",
        image: "/psylocke-backstory/X-Men_Vol_2_24.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#24",
        releaseDate: "September 1993",
    },
    {
        id: "xmen-2-25",
        image: "/psylocke-backstory/X-Men_Vol_2_25.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#25",
        releaseDate: "October 1993",
    },
    {
        id: "xmen-2-28",
        image: "/psylocke-backstory/X-Men_Vol_2_28.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#28",
        releaseDate: "January 1994",
    },
    {
        id: "xmen-2-31",
        image: "/psylocke-backstory/X-Men_Vol_2_31.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#31",
        releaseDate: "April 1994",
    },
    {
        id: "xmen-2-32",
        image: "/psylocke-backstory/X-Men_Vol_2_32.png",
        publisher: "Marvel Comics",
        title: "X-Men",
        volume: "Vol 2",
        issueNumber: "#32",
        releaseDate: "May 1994",
    },
    {
        id: "madripoor-1-1",
        image: "/psylocke-backstory/Hunt_for_Wolverine_Mystery_in_Madripoor_Vol_1_1.png",
        publisher: "Marvel Comics",
        title: "Hunt for Wolverine: Mystery in Madripoor",
        volume: "Vol 1",
        issueNumber: "#1",
        releaseDate: "July 2018",
    },
    {
        id: "madripoor-1-2",
        image: "/psylocke-backstory/Hunt_for_Wolverine_Mystery_in_Madripoor_Vol_1_2.png",
        publisher: "Marvel Comics",
        title: "Hunt for Wolverine: Mystery in Madripoor",
        volume: "Vol 1",
        issueNumber: "#2",
        releaseDate: "August 2018",
    },
    {
        id: "madripoor-1-3",
        image: "/psylocke-backstory/Hunt_for_Wolverine_Mystery_in_Madripoor_Vol_1_3.png",
        publisher: "Marvel Comics",
        title: "Hunt for Wolverine: Mystery in Madripoor",
        volume: "Vol 1",
        issueNumber: "#3",
        releaseDate: "September 2018",
    },
    {
        id: "madripoor-1-4",
        image: "/psylocke-backstory/Hunt_for_Wolverine_Mystery_in_Madripoor_Vol_1_4.png",
        publisher: "Marvel Comics",
        title: "Hunt for Wolverine: Mystery in Madripoor",
        volume: "Vol 1",
        issueNumber: "#4",
        releaseDate: "October 2018",
    },
    {
        id: "uncanny-5-16",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_5_16.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 5",
        issueNumber: "#16",
        releaseDate: "June 2019",
    },
    {
        id: "uncanny-5-17",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_5_17.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 5",
        issueNumber: "#17",
        releaseDate: "July 2019",
    },
    {
        id: "uncanny-5-18",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_5_18.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 5",
        issueNumber: "#18",
        releaseDate: "July 2019",
    },
    {
        id: "uncanny-5-19",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_5_19.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 5",
        issueNumber: "#19",
        releaseDate: "August 2019",
    },
    {
        id: "uncanny-5-20",
        image: "/psylocke-backstory/Uncanny_X-Men_Vol_5_20.png",
        publisher: "Marvel Comics",
        title: "Uncanny X-Men",
        volume: "Vol 5",
        issueNumber: "#20",
        releaseDate: "August 2019",
    },
    {
        id: "excalibur-4-1",
        image: "/psylocke-backstory/Excalibur_Vol_4_1.png",
        publisher: "Marvel Comics",
        title: "Excalibur",
        volume: "Vol 4",
        issueNumber: "#1",
        releaseDate: "December 2019",
    }
];
